-----------------------------------------------------------
-- Import Lua modules
-----------------------------------------------------------

require('settings')
require('keymaps')
require('plugins/packer')
require('plugins/sonokai')
require('plugins/nvim-cmp')
require('plugins/vim-maximizer')
require('plugins/nvim-tree')
require('plugins/rnvimr')
require('plugins/fzf-lua')
require('plugins/gitsigns')
require('plugins/git-messenger')
require('plugins/gitlinker')
require('plugins/lualine')
require('plugins/tree-sitter')
require('plugins/nvim-lspconfig')
require('plugins/nvim-ts-rainbow')
require('plugins/null-ls')
require('plugins/trouble')
require('plugins/toggleterm')
require('plugins/comment-nvim')
require('plugins/indent-blankline')
require('plugins/ansible-vim') -- TODO: not working
require('plugins/nvim-autopairs')
require('plugins/neoclip')
require('plugins/investigate')
require('plugins/matchup')
